services:
  postgresql:
    image: postgres:15.2-alpine
    pull_policy: missing
    container_name: planes_postgresql
    environment:
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: superpass
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data: