services:
  app:
    image: uaplanes:0.0.1
    container_name: uaplanes_app
    depends_on:
      - postgresql
    environment:
      DB_HOST: uaplanes_postgresql # use container_name of postgresql container (docker-compose supports DNS)
      DB_NAME: uaplanes
      DB_USER: pavel
      DB_PASSWORD: superpass
    ports:
      - "8080:8080"

  postgresql:
    image: postgres:15.2-alpine
    pull_policy: missing
    container_name: uaplanes_postgresql
    environment:
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: uaplanes
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data: